on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.G_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/gagan4580/27564580/my-react-app:latest .
          docker push ghcr.io/gagan4580/27564580/my-react-app:latest

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['Build and push Docker image']

    steps:
     - uses: actions/checkout@v3
        with:
          repository: gagan4580/gitops-infra
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "gagan4580@yahoo.com"
          git config --global user.name "gagan4580"
          echo ${{ github.sha }}      
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/gitops:${{ github.sha }}#g" deploy.yaml
          git add -A
          git commit -am "update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
