name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ...

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # ...

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 27564580/my-react-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: dckr_pat_y9r3zOkFgQNGK1Re6D-ACXa173Y
