name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker image
        env:
          DOCKER_IMAGE: 27564580/my-react-app:latest
          DOCKERFILE_PATH: docker/Dockerfile
        run: |
          docker build -t $DOCKER_IMAGE -f $DOCKERFILE_PATH .
          docker push $DOCKER_IMAGE

      - name: Tag and Push Docker image to GitHub Container Registry
        env:
          DOCKER_IMAGE: 27564580/my-react-app:latest
          IMAGE_TAG_SHA: ${{ github.sha }}
        run: |
          docker tag $DOCKER_IMAGE docker.pkg.github.com/gagan4580/my-react-app/${{ github.repository }}:${IMAGE_TAG_SHA}
          docker push docker.pkg.github.com/gagan4580/my-react-app/${{ github.repository }}:${IMAGE_TAG_SHA}
