stages:
  - build
  - test

build:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build

test:
  stage: test
  image: node:lts
  script:
    - npm install
    - npm test

# Only trigger the pipeline on pushes to the master branch
only:
  - master
