name: Build Step

on:
  push:
    branches: ['master']
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running tests"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          # Note: tags have to be all lower-case
          tags: |
            27564580/my-react-app:${{ github.sha }} 
            ghcr.io/gagan4580/27564580/my-react-app:${{ github.sha }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-deploy-file:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gagan4580/gitops-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}

      - name: Update Deployment File
        run: |
          sed -i "s#27564580/my-react-app:[0-9a-f]*#27564580/my-react-app:${{ steps.docker_build.outputs.digest }}#" deploy.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "gagan4580@yahoo.com"
          git config --global user.name "gagan4580"
          git add path/to/your/deploy/file.yaml
          git commit -m "Update image for - ${{ steps.docker_build.outputs.digest }}"
          git push origin master
