name: CI Pipeline

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "running tests"

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: ['test-stage']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            27564580/my-react-app:${{ github.sha }}
            ghcr.io/gagan4580/27564580/my-react-app:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        id: image_digest
        env:
          IMAGE_DIGEST: ${{ steps.docker_build.outputs.digest }}

  update-deploy-file:
    name: Update Deploy File
    needs: ['build-and-push-docker-image']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gitops-infra
        uses: actions/checkout@v3
        with:
          repository: gagan4580/gitops-infra
          token: ${{ secrets.G_TOKEN }}

      - name: Update Deployment File
        run: |
          sed -i "s@gagan4580/27564580/my-react-app:[0-9a-f]*@gagan4580/27564580/my-react-app:${{ needs.build-and-push-docker-image.outputs['image_digest'] }}@" deploy.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "gagan4580@yahoo.com"
          git config --global user.name "gagan4580"
          git add deploy.yaml
          git commit -m "Update image for - ${{ needs.build-and-push-docker-image.outputs['image_digest'] }}"
          git push origin master
